### ISSUE TITLE
Build shows nuget warnings

### ISSUE THREAD

**Issue by matt-richardson** [ASOS/OctopusStepTemplateCi#12]
See https://ci.appveyor.com/project/paulmarsy/octopussteptemplateci

```
WARNING: 57 issue(s) found with package 'OctopusStepTemplateCi'.
 
Issue: PowerShell file outside tools folder.
Description: The script file 'Cmdlets\Interface\Invoke-OctopusScriptTestSuite.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package.
Solution: Move it into the 'tools' folder.
 
Issue: PowerShell file outside tools folder.
Description: The script file 'Cmdlets\Interface\Invoke-OctopusScriptTestSuite.Tests.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package.
Solution: Move it into the 'tools' folder.
 
Issue: PowerShell file outside tools folder.
Description: The script file 'Cmdlets\Interfac
...
```

This shoud be an easy fix - just need to add `-NoPackageAnalysis` to the nuget command. See https://docs.nuget.org/consume/command-line-reference#user-content-pack-command-options.

**Comment by paulmarsy** [comment]
Should be fixed in #13.. avoiding clicking the 'new build' button to see if the CI pipeline picks up the new commit and works

Might change the version numbers if CI works well... an incremented revision & new github release for every commit is a bit heavy
Maybe a static prerelease github release which always has the latest build, and powershellgallery is fine to continue just being pushed to, then version number bumps are manual when its appropriate

**Comment by paulmarsy** [comment]
@matt-richardson this reminds me, one for a different issue but I was thinking of putting an exclude for *.Tests.ps1 in the nuspec file - the pester tests are a compilation entity and don't really belong in the deployable nuget package, plus they take up (a small amount of) space and won't be run once packaged up

That would also exclude the scriptvalidationtests, having them suffixed with .Tests.ps1 was just so they followed the existing pattern or because something else expects it to have that suffix?
If its the former then the same way step templates and script modules have their own suffix pattern how about *.ScriptValidationsTests.ps1 for them? Makes them distinct from normal unit tests and makes the above exclusion simpler

**Comment by paulmarsy** [comment]
Warnings have been removed :smile: ]
https://ci.appveyor.com/project/paulmarsy/octopussteptemplateci/build/1.0.25
